pipeline {
    agent {
        docker {
            image 'jenkins-with-docker-ansible:latest'
            //args '-u root:root'
        }
    }

    environment {
        JIRA_URL = 'https://on-off-board-automation.atlassian.net'
        JIRA_EMAIL = 'minjung10402@gmail.com'
        JIRA_PROJECT = 'HR'
    }

    stages {
		stage('Clean Workspace') {
            steps {
                echo "Cleaning workspace..."
                cleanWs()
            }
        }
		
        stage('Initialize') {
            steps {
                script {
                    // Global list accessible in later stages
                    EMPLOYEES_TO_RUN = []
                }
            }
        }

        stage('Checkout Code') {
            steps {
                echo "Checking out code..."
                checkout scm
            }
        }

		stage('Update Employee Actions') {
    		steps {
        		script {
            		echo "Updating employee actions based on start/end dates..."
            		sh 'python3 scripts/update_employees.py'
            		echo "✔ Employee YAMLs updated"
        		}
    		}
		}

        stage('Detect Employees to Process') {
            steps {
                script {
                    echo "Scanning employees directory..."

                    def EMPLOYEES = sh(
                        script: "ls employees/*.yml",
                        returnStdout: true
                    ).trim().split('\n')

                    echo "Found employee files:"
                    EMPLOYEES.each { println " - ${it}" }

                    // Filter only employees with action onboard/offboard
                    //EMPLOYEES_TO_RUN.clear()

                    for (file in EMPLOYEES) {
                        def data = readYaml file: file
                        def action = data.employee.action ?: "NONE"

                        if (action == "ONBOARD" || action == "OFFBOARD") {
                            EMPLOYEES_TO_RUN.add([file: file, action: action])
                        }
                    }

                    if (EMPLOYEES_TO_RUN.isEmpty()) {
                        error "No employees require onboarding or offboarding."
                    }

                    echo "\nEmployees requiring actions:"
                    EMPLOYEES_TO_RUN.each { println " - ${it.file} (${it.action})" }
                }
            }
        }

        stage('Process Each Employee') {
            steps {
                script {

                    for (emp in EMPLOYEES_TO_RUN) {

                        def file = emp.file
                        def action = emp.action

                        echo "\n==============================="
                        echo "Processing: ${file}"
                        echo "Action: ${action}"
                        echo "==============================="

                        // Load YAML
                        def data = readYaml file: file
                        env.EMPLOYEE_NAME = data.employee.name
                        env.EMPLOYEE_EMAIL = data.employee.email
                        env.MANAGER_EMAIL = data.employee.manager

                        echo "Employee: ${env.EMPLOYEE_NAME}"
                        echo "Email: ${env.EMPLOYEE_EMAIL}"
                        echo "Manager: ${env.MANAGER_EMAIL}"

                        /**************
                         * CREATE JIRA TICKET
                         **************/
                        echo "Creating Jira ticket..."

                        withCredentials([string(credentialsId: 'jira-api-token', variable: 'JIRA_API_TOKEN')]) {
                            def result = sh(
                                script: """
                                    python3 scripts/create-jira-ticket.py \
										create \
                                        '${env.EMPLOYEE_NAME}' \
                                        '${env.EMPLOYEE_EMAIL}' \
                                        '${action}'
                                """,
                                returnStdout: true
                            ).trim()

                            env.JIRA_TICKET = result.split('=')[1]
							echo "✔ Jira created: ${env.JIRA_TICKET}"



							// Transition to In Progress
                            echo "Moving ticket to In Progress..."
                            sh """
                                export JIRA_API_TOKEN='${JIRA_API_TOKEN}'
                                python3 scripts/create-jira-ticket.py transition '${env.JIRA_TICKET}' 'In Progress'
                            """
                        }

                        /**************
                         * RUN ANSIBLE
                         **************/
                        echo "Running Ansible for: ${action}"

                        if (action == "ONBOARD") {
                            sh """
                                ansible-playbook ansible/playbooks/onboard.yml \
                                    -i ansible/inventory/hosts \
                                    -e "employee_name='${env.EMPLOYEE_NAME}'" \
                                    -e "employee_email='${env.EMPLOYEE_EMAIL}'"
                            """
                        } else if (action == "OFFBOARD") {
                            sh """
                                ansible-playbook ansible/playbooks/offboard.yml \
                                    -i ansible/inventory/hosts \
                                    -e "employee_name='${env.EMPLOYEE_NAME}'" \
                                    -e "employee_email='${env.EMPLOYEE_EMAIL}'"
                            """
                        }

                        echo "✔ Ansible execution complete"

						/**************
                         * MARK JIRA DONE
                         **************/
                        echo "Marking Jira ticket as Done..."
                        withCredentials([string(credentialsId: 'jira-api-token', variable: 'JIRA_API_TOKEN')]) {
                            sh """
                                export JIRA_API_TOKEN='${JIRA_API_TOKEN}'
                                python3 scripts/create-jira-ticket.py transition '${env.JIRA_TICKET}' 'Done'
                            """
                        }
                        echo "✔ Jira ticket ${env.JIRA_TICKET} marked as Done"


                        /**************
                         * SEND WEBEX
                         **************/
                        echo "Sending Webex notification..."

                        withCredentials([
                            string(credentialsId: 'webex-bot-token', variable: 'WEBEX_BOT_TOKEN'),
                            string(credentialsId: 'webex-room-id', variable: 'WEBEX_ROOM_ID')
                        ]) {
                            sh """
                                python3 scripts/send-webex-notif.py \
                                    '${env.EMPLOYEE_NAME}' \
                                    '${action}' \
                                    '${env.JIRA_TICKET}' \
                                    '${env.MANAGER_EMAIL}'
                            """
                        }

                        echo "✔ Webex notification sent to ${env.MANAGER_EMAIL}"

                    } // end for loop
                }
            }
        }
    }

    post {
        success {
            echo "✔ Automated onboarding/offboarding pipeline completed successfully!"
        }
        failure {
            echo "❌ Pipeline failed. Check logs."
        }
    }
}

'''
pipeline {
	agent {
		docker {
			image 'jenkins-with-docker-ansible:latest'
			args '-u root:root'
		}
	}
	
	parameters {
		choice(name: 'ACTION', choices: ['onboard', 'offboard'], description: 'Select action')
		string(name: 'EMPLOYEE_FILE', defaultValue: 'jane_doe.yml', description: 'Employee YAML filename')
	}

	environment {
		EMPLOYEE_PATH = "employees/${params.EMPLOYEE_FILE}"
		JIRA_URL = 'https://on-off-board-automation.atlassian.net'
		JIRA_EMAIL = 'minjung10402@gmail.com'
		JIRA_PROJECT = 'HR'
	}
	
	stages {
		stage('Checkout Code') {
			steps {
				echo "Checking out code from GitHub ..."
				checkout scm
			}
		}

		stage('Parse Employee Data') {
			steps {
				script {
					echo "Reading employee file: ${EMPLOYEE_PATH}"

					// Read YAML file
					def employeeData = readYaml file: "${EMPLOYEE_PATH}"

					// Extract YAML file
					env.EMPLOYEE_NAME = employeeData.employee.name
					env.EMPLOYEE_EMAIL = employeeData.employee.email
					env.EMPLOYEE_ROLE = employeeData.employee.role
					env.EMPLOYEE_TEAM = employeeData.employee.team
					env.MANAGER_EMAIL = employeeData.employee.manager
	
					echo "Processing ${params.ACTION} for: ${env.EMPLOYEE_NAME}"
					echo "Email: ${env.EMPLOYEE_EMAIL}"
					echo "Role: ${env.EMPLOYEE_ROLE}"
					echo "Team: ${env.EMPLOYEE_TEAM}"
					echo "Manager: ${env.MANAGER_EMAIL}"
				}
			}
		}
		
		stage('Create Jira Ticket') {
			steps {
				script {
					echo "Creating Jira ticket for ${env.EMPLOYEE_NAME}"
					
					withCredentials([string(credentialsId: 'jira-api-token', variable: 'JIRA_API_TOKEN')]) {
						def result = sh(
							script: """
								python3 scripts/create-jira-ticket.py \
									'${env.EMPLOYEE_NAME}' \
									'${env.EMPLOYEE_EMAIL}' \
									'${params.ACTION}'
							""",
							returnStdout: true
						).trim()
						
					// Extract ticket key from ouput
					env.JIRA_TICKET = result.split('=')[1]
					echo "✅ Jira ticket created: ${env.JIRA_TICKET}"
					}
				}
			}
		}
	
		stage('Run Ansible Playbook') {
			steps {
				script {
					echo "Running Ansible playbook for ${params.ACTION} ..."
					
					if (params.ACTION == 'onboard') {
						sh """
							ansible-playbook ansible/playbooks/onboard.yml \
								-i ansible/inventory/hosts \
								-e "employee_name='${env.EMPLOYEE_NAME}'" \
								-e "employee_email='${env.EMPLOYEE_EMAIL}'"
						"""
					} else {
						sh """
							ansible-playbook ansible/playbooks/offboard.yml \
								-i ansible/inventory/hosts \
								-e "employee_name='${env.EMPLOYEE_NAME}'" \
								-e "employee_email='${env.EMPLOYEE_EMAIL}'"

						"""
					}
				}
			}
		}
		
		stage('Send Webex Notifcation') {
			steps {
				script {
					echo "Sending Webex notication ..."
					
					withCredentials([
						string(credentialsId: 'webex-bot-token', variable: 'WEBEX_BOT_TOKEN'),
						string(credentialsId: 'webex-room-id', variable: 'WEBEX_ROOM_ID')
					]) {
						sh """
							python3 scripts/send-webex-notif.py \
								'${env.EMPLOYEE_NAME}' \
								'${params.ACTION}' \
								'${env.JIRA_TICKET}' \
								'${env.MANAGER_EMAIL}'
						"""
					}
					echo "✅ Notification sent to ${env.MANAGER_EMAIL}"
					//echo "${params.ACTION.capitalize()} completed for ${env.EMPLOYEE_NAME}"
					//placeholder for webex
				}
			}
		}
	}
	
	post {
		success {
			echo "Pipeline completed successfully!"
			echo "Employee: ${env.EMPLOYEE_NAME}"
			echo "Action: ${params.ACTION}"
			echo "Jira Ticket: ${env.JIRA_TICKET}"
		}
		failure {
			echo "Pipeline failed. Check logs above."
		}
	}
}
'''
